language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"

script:
  - export GITHUB_REPO=$(pwd)
  - git clone https://github.com/Sable/wu-wei-benchmarking-toolkit.git /tmp/wu && cd /tmp/wu && npm install && npm link
  - mkdir /tmp/test && cd /tmp/test
  - wu init
  - wu platform --save --short-name travis
  - wu install --compatibilities $GITHUB_REPO
  - wu run
  - wu report
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - github@ericklavoie.com
    on_success: change
    on_failure: always
  slack: sable-mclab:BCSCOEsSkQxkbBoNbuwrzVTC
